project:
  type: website
  output-dir: docs

website:
  title: "lab7"
  navbar:
    left:
      - href: index.qmd
        text: Главная страница
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



